// <auto-generated />
using HOUPE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HOUPE.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20191027085750_v6")]
    partial class v6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HOUPE.Models.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cost");

                    b.Property<string>("Information");

                    b.Property<string>("Nutrition");

                    b.Property<int>("QuantityNight")
                        .HasMaxLength(2);

                    b.Property<int>("ToursId");

                    b.Property<string>("TypeOfRooms");

                    b.Property<string>("hotel");

                    b.HasKey("Id");

                    b.HasIndex("ToursId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("HOUPE.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageAdress");

                    b.Property<string>("Tourss")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("HOUPE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<bool>("Type");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HOUPE.Models.UsersImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageAdress");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersImages");
                });

            modelBuilder.Entity("HOUPE.Models.UsersRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("QuantityOrders");

                    b.Property<string>("Status");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersRooms");
                });

            modelBuilder.Entity("HOUPE.Models.Hotel", b =>
                {
                    b.HasOne("HOUPE.Models.Tour", "Tours")
                        .WithMany("Hotels")
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HOUPE.Models.UsersImage", b =>
                {
                    b.HasOne("HOUPE.Models.User", "Users")
                        .WithOne("UsersImages")
                        .HasForeignKey("HOUPE.Models.UsersImage", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HOUPE.Models.UsersRoom", b =>
                {
                    b.HasOne("HOUPE.Models.User", "Users")
                        .WithOne("UsersRooms")
                        .HasForeignKey("HOUPE.Models.UsersRoom", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
